import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — PlanPal",
};

const LAST_UPDATED = "29 May 2026";

export default function TermsPage() {
  return (
    <>
      <Navbar user={null} />
      <main className="min-h-screen pt-24 pb-16 px-4">
        <div className="mx-auto max-w-2xl">

          <div className="mb-8">
            <Link
              href="/"
              className="inline-flex items-center gap-1.5 text-sm text-text-dim hover:text-text-bright transition-colors duration-200"
            >
              <ArrowLeft size={14} />
              Back to home
            </Link>
          </div>

          <h1 className="font-display text-4xl font-bold gradient-text mb-2">Terms of Service</h1>
          <p className="text-text-dim text-sm mb-10">Last updated: {LAST_UPDATED}</p>

          <div className="space-y-10 text-text-bright/80 text-sm leading-relaxed">

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">1. Acceptance of terms</h2>
              <p>
                By accessing or using PlanPal ("the Service"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use the Service. These terms apply to all users, including visitors, registered users, and group members.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">2. The service</h2>
              <p className="mb-3">
                PlanPal is an AI-powered group activity planning tool. The Service allows you to:
              </p>
              <ul className="space-y-2">
                {[
                  "Complete a personality quiz to discover your archetype",
                  "Select personal interests from a curated list",
                  "Create and join groups with other users",
                  "Receive AI-generated activity recommendations tailored to your group",
                  "Vote on recommendations within your group",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span className="text-violet mt-0.5">→</span>
                    {item}
                  </li>
                ))}
              </ul>
              <p className="mt-3">
                AI recommendations are generated by a third-party language model and are provided for informational and entertainment purposes. We do not guarantee their accuracy, suitability, or availability of any suggested activities.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">3. Your account</h2>
              <p>
                You must sign in with a valid Google account to use PlanPal. You are responsible for maintaining the security of your account and for all activity that occurs under it. You must not share your account credentials with others. You must be at least 13 years old to use the Service.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">4. Acceptable use</h2>
              <p className="mb-3">You agree not to:</p>
              <ul className="space-y-2">
                {[
                  "Use the Service for any unlawful purpose",
                  "Harass, abuse, or harm other users",
                  "Attempt to gain unauthorised access to any part of the Service",
                  "Reverse-engineer, scrape, or copy the Service or its content",
                  "Use the Service to send spam or unsolicited communications",
                  "Impersonate another person or entity",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span className="text-pink mt-0.5">→</span>
                    {item}
                  </li>
                ))}
              </ul>
              <p className="mt-3">
                We reserve the right to suspend or terminate accounts that violate these terms without notice.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">5. Content and intellectual property</h2>
              <p>
                All content you provide (quiz responses, interests, group names) remains yours. By using the Service, you grant PlanPal a limited licence to use this content to operate and improve the Service. The PlanPal name, logo, and interface design are our intellectual property and may not be reproduced without permission.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">6. AI-generated content</h2>
              <p>
                Activity recommendations are generated by an AI language model. They are provided as suggestions only. PlanPal does not endorse any specific business, venue, or activity. Always exercise your own judgement when following any recommendation. We are not responsible for any outcome resulting from acting on AI-generated suggestions.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">7. Availability and changes</h2>
              <p>
                We aim to keep PlanPal available at all times, but we do not guarantee uninterrupted access. We may modify, suspend, or discontinue any part of the Service at any time, with or without notice. We may also update these Terms — continued use of the Service after changes constitutes your acceptance.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">8. Disclaimer of warranties</h2>
              <p>
                The Service is provided "as is" and "as available", without warranty of any kind, express or implied. We do not warrant that the Service will be error-free, uninterrupted, or that results obtained from it will be accurate or reliable.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">9. Limitation of liability</h2>
              <p>
                To the fullest extent permitted by law, PlanPal shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service, even if we have been advised of the possibility of such damages.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">10. Governing law</h2>
              <p>
                These Terms are governed by the laws of the jurisdiction in which PlanPal operates, without regard to conflict-of-law principles.
              </p>
            </section>

            <section>
              <h2 className="font-display text-lg font-semibold text-text-bright mb-3">11. Contact</h2>
              <p>
                Questions about these Terms? Reach us at{" "}
                <a href="mailto:hello@planpal.app" className="text-violet hover:underline">
                  hello@planpal.app
                </a>.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
